name: Label Issues (Script Injection)
on:
  issues:
    types:
      - opened

jobs:
  assign-label:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Add a Label
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          issue_title: "${{ github.event.issue.title }}"

        run: |
          if [[ "$issue_title" == *"bug"* ]]; then
            echo "Issue is about a bug!"
            echo "Assigning Label - BUG ...................................."
          else
            echo "Not a bug"
          fi