name: solar system workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**
# 🟢 बदल १: आपण गिटहब सिक्रेटमधून थेट पूर्ण कनेक्शन स्ट्रिंग इथे पास करत आहोत
env:
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  unit-testing:
    name: Unit Testing
    environment:
      name: development
    services:
      mongo-db:
        image: tukaram124/solar-system-db:v1
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ vars.DB_NAME }}

    env:
      MONGO_URI: mongodb://${{ vars.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@localhost:27017/${{ vars.DB_NAME }}?authSource=admin
      MONGO_USERNAME: ${{ vars.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    strategy:
      matrix:
        node-version: [18, 20]
        operating-system: [ubuntu-latest] ## macos-latest वरून काढलं आहे कारण node 18 साठी काही एरर्स येत आहेत, आणि node 20 साठी macos वर अजून सपोर्ट नाहीये
        exclude:
          - node-version: 18
            operating-system: macos-latest
    runs-on: ${{ matrix.operating-system }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 💡 टीप: इथे मी setup-node चं व्हर्जन सुद्धा v3 वरून v4 केलं आहे, जेणेकरून एरर्स येणार नाहीत
      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Unit Testing
        id: nodejs-unit-testing-step
        run: npm test -- --timeout 15000

      - name: Archive Test Result
        if: always()  # हे सुनिश्चित करेल की टेस्ट फेल झाल्यासही हा स्टेप रन होईल
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-test-result
          path: test-results.xml
  
  code-coverage:
    name: Code Coverage
    environment:
      name: development
    container:
      image: node:18
    services:
      mongo-db:
        image: tukaram124/solar-system-db:v1
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ vars.DB_NAME }}

    env:
      MONGO_URI: mongodb://${{ vars.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@localhost:27017/${{ vars.DB_NAME }}?authSource=admin
      MONGO_USERNAME: ${{ vars.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     # - name: Set up Node.js Version 18
     #   uses: actions/setup-node@v4
     #   with:
     #     node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB..."
          sleep 20

      - name: Check code coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5

  docker:
    name: docker-Containerization
    needs: [unit-testing, code-coverage]
    #environment:
     # name: development
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Test DB MongoDB Image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/solar-system-db:v1 -f ./Dockerfile.mongo .
          docker push ${{ vars.DOCKERHUB_USERNAME }}/solar-system-db:v1

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build for Testing
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Docker Image Testing
        run: |
          docker images
          docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          sleep 3
          export IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo "Container IP: $IP"

          echo Testing Image URL using wget
          wget -q -O - 127.0.0.1:3000/live | grep live

      # १. फक्त डॉकर हबसाठी बिल्ड आणि पुश
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      # २. फक्त GHCR साठी बिल्ड आणि पुश (आता हे फेल झालं तरी वरचं काम झालेलं असेल)
      - name: Push to GitHub Packages (GHCR)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/tukaram-k8s/solar-system:${{ github.sha }}

  dev-deployment:
    name: Deploy to Development Environment
    needs: docker
    environment: 
      name: development
      url: https://${{ steps.set-dev-app-ingress-url.outputs.DEV_APP_INGRESS_HOST }}
    outputs:
      DEV_APP_INGRESS_URL: ${{ steps.set-dev-app-ingress-url.outputs.DEV_APP_INGRESS_HOST }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Development Environment
        run: |
          echo "Deploying to development environment..."
          
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

     # - name: Create Kubernetes Kind Cluster
     #   uses: helm/kind-action@v1
     # we are updating the create k8s kind cluster step to use our custom kind-config.yaml file, which has the necessary port mappings for ingress to work properly
      - name: Create Kubernetes Kind Cluster
        uses: helm/kind-action@v1
        with:
          config: kind-config.yaml

      - name: Install NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          # इथे आपण थोडा वेळ देतोय की इन्ग्रेस कंट्रोलर पूर्णपणे तयार होईपर्यंत थांबण्यासाठी, कारण कधीकधी तो तयार होण्यासाठी थोडा वेळ घेतो
          echo "Waiting for NGINX Ingress Controller to be ready..."
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=120s

      - name: Verify Cluster Creation
        run: |
          kubectl version --client=true
          kubectl cluster-info
          kubectl get nodes

      - name: Create Namespace
        run: |
          kubectl create namespace ${{ vars.DEV_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          echo "Namespace created"

      - name: Set INGRESS_IP variable
        run: echo "INGRESS_IP=127.0.0.1" >> $GITHUB_ENV

      - name: Replace Token in Manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.DEV_NAMESPACE }}
          REPLICAS: ${{ vars.DEV_REPLICAS }}
          K8S_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Check files
        run: |
          echo "Checking the replaced manifest files..."
          cat kubernetes/development/*.yaml

      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ vars.DEV_NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI='mongodb://${{ vars.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017/${{ vars.DB_NAME }}?authSource=admin' \
            --from-literal=MONGO_USERNAME='${{ vars.MONGO_USER }}' \
            --from-literal=MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
            --save-config \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Verify MongoDB Secret
        run: |
          kubectl -n ${{ vars.DEV_NAMESPACE }} get secret mongo-db-creds -o jsonpath="{.data.MONGO_USERNAME}" | base64 -d
          echo

      - name: Deploy to Development Environment
        run: |
          # आधी deployment आणि service अप्लाय करा
          kubectl apply -f kubernetes/development/deployment.yaml -n ${{ vars.DEV_NAMESPACE }}
          kubectl apply -f kubernetes/development/service.yaml -n ${{ vars.DEV_NAMESPACE }}
          
          # थोडा वेळ थांबा
          sleep 10
          
          # शेवटी ingress अप्लाय करा
          kubectl apply -f kubernetes/development/ingress.yaml -n ${{ vars.DEV_NAMESPACE }}

      - name: Verify Development Deployment
        run: |
          kubectl -n ${{ vars.DEV_NAMESPACE }} get all
          kubectl get ingress -n ${{ vars.DEV_NAMESPACE }}
          kubectl get secrets -n ${{ vars.DEV_NAMESPACE }}

      - name: Verify Environment Values
        run: |
          echo "Environment: Development"
          echo "DB_NAME=${{ vars.DB_NAME }}"
          echo "MONGO_USER=${{ vars.MONGO_USER }}"

      - name: Set Dev App Ingress Host URL
        id: set-dev-app-ingress-url
        run: |
          echo "DEV_APP_INGRESS_HOST=127.0.0.1" >> "$GITHUB_OUTPUT"

      - name: Start Port Forwarding
        run: |
          # १. पॉड रेडी होण्याची वाट पाहा (वेळ १८० सेकंद केलाय)
          kubectl rollout status deployment/solar-system -n development --timeout=90s || (kubectl describe deployment/solar-system -n development && kubectl get pods -n development && exit 1)
          
          # २. पोर्ट फॉरवर्डिंग
          kubectl port-forward svc/solar-system -n development 3000:3000 --address 0.0.0.0 &
          sleep 10

      - name: Run DEV Integration Tests
        run: |
          echo "Testing the application using localhost:3000"
          
          # १. curl वापरून डेटा मिळवणे आणि jq वापरून 'status' तपासणे
          RESPONSE=$(curl -s http://localhost:3000/live)
          STATUS=$(echo $RESPONSE | jq -r '.status')
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/live)

          echo "Response Status: $STATUS"
          echo "HTTP Code: $HTTP_CODE"

          # २. कंडिशन चेक करणे
          if [ "$HTTP_CODE" -eq 200 ] && [ "$STATUS" == "live" ]; then
            echo "Integration test passed successfully!"
          else
            echo "Integration test failed!"
            exit 1
          fi

  prod-deployment:
    name: Deploy to Production Environment
    if: github.ref == 'refs/heads/main'
    needs: dev-deployment
    environment: 
      name: production
      url: https://${{ steps.set-prod-app-ingress-url.outputs.PROD_APP_INGRESS_HOST }}
    outputs:
      PROD_APP_INGRESS_URL: ${{ steps.set-prod-app-ingress-url.outputs.PROD_APP_INGRESS_HOST }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production Environment
        run: |
          echo "Deploying to production environment..."
          
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

     # - name: Create Kubernetes Kind Cluster
     #   uses: helm/kind-action@v1
     # we are updating the create k8s kind cluster step to use our custom kind-config.yaml file, which has the necessary port mappings for ingress to work properly
      - name: Create Kubernetes Kind Cluster for Production
        uses: helm/kind-action@v1
        with:
          config: kind-config.yaml

      - name: Install NGINX Ingress Controller for Production
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          # इथे आपण थोडा वेळ देतोय की इन्ग्रेस कंट्रोलर पूर्णपणे तयार होईपर्यंत थांबण्यासाठी, कारण कधीकधी तो तयार होण्यासाठी थोडा वेळ घेतो
          echo "Waiting for NGINX Ingress Controller to be ready..."
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=120s

      - name: Verify Cluster Creation for Production
        run: |
          kubectl version --client=true
          kubectl cluster-info
          kubectl get nodes

      - name: Create Namespace in kind cluster for Production
        run: |
          kubectl create namespace ${{ vars.PROD_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          echo "PROD Namespace created"

      - name: Set INGRESS_IP variable
        run: echo "INGRESS_IP=127.0.0.1" >> $GITHUB_ENV

      - name: Replace Token in Manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: '["kubernetes/production/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.PROD_NAMESPACE }}
          REPLICAS: ${{ vars.PROD_REPLICAS }}
          K8S_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Check files
        run: |
          echo "Checking the replaced manifest files..."
          cat kubernetes/production/*.yaml

      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ vars.PROD_NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI='mongodb://${{ vars.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017/${{ vars.DB_NAME }}?authSource=admin' \
            --from-literal=MONGO_USERNAME='${{ vars.MONGO_USER }}' \
            --from-literal=MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
            --save-config \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Verify MongoDB Secret
        run: |
          kubectl -n ${{ vars.PROD_NAMESPACE }} get secret mongo-db-creds -o jsonpath="{.data.MONGO_USERNAME}" | base64 -d
          echo

      - name: Deploy to Production Environment
        run: |
          # आधी deployment आणि service अप्लाय करा
          kubectl apply -f kubernetes/production/deployment.yaml -n ${{ vars.PROD_NAMESPACE }}
          kubectl apply -f kubernetes/production/service.yaml -n ${{ vars.PROD_NAMESPACE }}
          
          # थोडा वेळ थांबा
          sleep 10
          
          # शेवटी ingress अप्लाय करा
          kubectl apply -f kubernetes/production/ingress.yaml -n ${{ vars.PROD_NAMESPACE }}

      - name: Verify Production Deployment
        run: |
          kubectl -n ${{ vars.PROD_NAMESPACE }} get all
          kubectl get ingress -n ${{ vars.PROD_NAMESPACE }}
          kubectl get secrets -n ${{ vars.PROD_NAMESPACE }}

      - name: Verify Environment Values
        run: |
          echo "Environment: Production"
          echo "DB_NAME=${{ vars.DB_NAME }}"
          echo "MONGO_USER=${{ vars.MONGO_USER }}"

      - name: Set Prod App Ingress Host URL
        id: set-prod-app-ingress-url
        run: |
          echo "PROD_APP_INGRESS_HOST=127.0.0.1" >> "$GITHUB_OUTPUT"

      - name: Start Port Forwarding
        run: |
          # १. पॉड रेडी होण्याची वाट पाहा (वेळ १८० सेकंद केलाय)
          kubectl rollout status deployment/solar-system -n production --timeout=90s || (kubectl describe deployment/solar-system -n production && kubectl get pods -n production && exit 1)
          
          # २. पोर्ट फॉरवर्डिंग
          kubectl port-forward svc/solar-system -n production 3000:3000 --address 0.0.0.0 &
          sleep 10

      - name: Run PROD Integration Tests
        run: |
          echo "Testing the application using localhost:3000"
          
          # १. curl वापरून डेटा मिळवणे आणि jq वापरून 'status' तपासणे
          RESPONSE=$(curl -s http://localhost:3000/live)
          STATUS=$(echo $RESPONSE | jq -r '.status')
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/live)

          echo "Response Status: $STATUS"
          echo "HTTP Code: $HTTP_CODE"

          # २. कंडिशन चेक करणे
          if [ "$HTTP_CODE" -eq 200 ] && [ "$STATUS" == "live" ]; then
            echo "Integration test passed successfully!"
          else
            echo "Integration test failed!"
            exit 1
          fi