name: solar system workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**

# 🟢 बदल १: आपण गिटहब सिक्रेटमधून थेट पूर्ण कनेक्शन स्ट्रिंग इथे पास करत आहोत
env:
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        node-version: [18, 19, 20]
        operating-system: [ubuntu-latest, macos-latest]
        exclude:
          - node-version: 18
            operating-system: macos-latest
    runs-on: ${{ matrix.operating-system }}
    
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 💡 टीप: इथे मी setup-node चं व्हर्जन सुद्धा v3 वरून v4 केलं आहे, जेणेकरून एरर्स येणार नाहीत
      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit_tests
        run: npm test || true

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-test-result
          path: test-results.xml
 
          
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check code coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5