name: solar system workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**

# 🟢 बदल १: आपण गिटहब सिक्रेटमधून थेट पूर्ण कनेक्शन स्ट्रिंग इथे पास करत आहोत
env:
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  unit-testing:
    name: Unit Testing
    services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod
        ports:
          - 27017:27017
    env:
      MONGO_URI: 'mongodb://localhost:27017/superData'
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password
    strategy:
      matrix:
        node-version: [18, 20]
        operating-system: [ubuntu-latest] ## macos-latest वरून काढलं आहे कारण node 18 साठी काही एरर्स येत आहेत, आणि node 20 साठी macos वर अजून सपोर्ट नाहीये
        exclude:
          - node-version: 18
            operating-system: macos-latest
    runs-on: ${{ matrix.operating-system }}
    
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 💡 टीप: इथे मी setup-node चं व्हर्जन सुद्धा v3 वरून v4 केलं आहे, जेणेकरून एरर्स येणार नाहीत
      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Unit Testing
        id: nodejs-unit-testing-step
        run: npm test -- --timeout 15000

      - name: Archive Test Result
        if: always()  # हे सुनिश्चित करेल की टेस्ट फेल झाल्यासही हा स्टेप रन होईल
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-test-result
          path: test-results.xml
 
          
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Check code coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5

  docker:
    name: Containerization
    needs: [unit-testing, code-coverage]
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build for Testing
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Docker Image Testing
        run: |
          docker images
          docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          sleep 3
          export IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo "Container IP: $IP"

          echo Testing Image URL using wget
          wget -q -O - 127.0.0.1:3000/live | grep live

      # १. फक्त डॉकर हबसाठी बिल्ड आणि पुश
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      # २. फक्त GHCR साठी बिल्ड आणि पुश (आता हे फेल झालं तरी वरचं काम झालेलं असेल)
      - name: Push to GitHub Packages (GHCR)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/tukaram-k8s/solar-system:${{ github.sha }}